baseurl = "https://seandavi.github.io/" # make sure to end in /
title = "seandavi(s12)"
copyright = "&copy; 2017 Sean Davis"
theme = "blackburn"
enableEmoji = true
#canonifyurls = true
footnotereturnlinkcontents = "<sup>^</sup>"

# ignore blogdown files:
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[blackfriday]
  hrefTargetBlank = true
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Sean Davis @ NCI"
  brand = "seandavi(s12)"
  googleAnalytics = "UA-93043521-1"
  disqus = "seandavi-github-io"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["yaml"]
  dateFormat = "02 Jan 2006, 15:04"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  # custom_css = ["css/my.css"]
  # custom_js = ["js/my.js"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Talks"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1.5
    identifier = "talk"
    url = "/talk/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 2
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 3
    url = "/contact/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # SNS microblogging
  twitter = "seandavis12"
  # gnusocial = "*" # Specify href (e.g. https://quitter.se/yourusername)
  # facebook = "*"
  # googleplus = "*"
  # weibo = "*"
  # tumblr = "*"

  # SNS career oriented
  linkedin = "seandavi"
  # xing = "*"

  # SNS news
  # reddit = "*"
  # hackernews = "*"

  # Techie
  github = "seandavi"
  # gitlab = "*"
  bitbucket = "seandavi"
  # stackoverflow = "seandavi"
  # serverfault = "seandavi"

  # SNS photo/video sharing
  # instagram = "*"
  # flickr = "*"
  # photo500px = "*"
  # pinterest = "*"
  # youtube = "*"
  # vimeo = "*"
  # vine = "*"
  slideshare = "seandavi"

  # Gaming
  # steam = "*"
  # mobygames = "*"

  # Music
  # lastfm = "*"
  # discogs = "*"

  # Other
  # keybase = "*"